Lint/HandleExceptions:
  Exclude:
    - 'lib/dotenv/rails.rb'

Style/Documentation:
  Exclude:
    - 'Rakefile'
    - 'lib/dotenv/version.rb'

Style/FileName:
  Exclude:
    - 'lib/dotenv/rails-now.rb'
    - 'lib/dotenv-rails.rb'

Style/HashSyntax:
  EnforcedStyle: 'hash_rockets'

Style/StringLiterals:
  EnforcedStyle: 'double_quotes'
